image: docker:stable

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_TAG: $TARGET-$CI_COMMIT_SHORT_SHA
  CONTAINER_IMAGE: $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/ubuntu-gtest
  CONTAINER_TAR_FILE: $CI_PROJECT_NAMESPACE.$CI_PROJECT_NAME.ubuntu-gtest.$TARGET-$CONTAINER_TAG.tar

before_script:
  - apk update
  - apk add make
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker info

###################################################################################################

## Build Image template
.build:
  stage: build
  script: 
    - docker pull $CI_REGISTRY/$CONTAINER_IMAGE:$CONTAINER_TAG || true
    - make TARGET=$TARGET CACHE_FROM=$CI_REGISTRY/$CONTAINER_IMAGE:$CONTAINER_TAG
    - docker save --output $CONTAINER_TAR_FILE $CONTAINER_IMAGE:$CONTAINER_TAG
  artifacts:
    paths:
      - $CONTAINER_TAR_FILE
    expire_in: 1 day
  only:
    variables:
      - $TARGET

## Deploy Image template
.deploy:
  stage: deploy
  script:
    - docker load --input $CONTAINER_TAR_FILE
    - docker tag $CONTAINER_IMAGE:$CONTAINER_TAG $CI_REGISTRY/$CONTAINER_IMAGE:$TARGET-latest
    - docker push $CI_REGISTRY/$CONTAINER_IMAGE:$TARGET-latest
  only:
    variables:
      - $TARGET
    refs:
      - master

###################################################################################################

### Intel
build:x86_64:
  extends: .build
  variables:
    TARGET: x86_64

deploy:x86_64:
  extends: .deploy
  variables:
    TARGET: x86_64
  dependencies:
    - build:x86_64

###################################################################################################

### ARMv7
build:armhf:
  extends: .build
  variables:
    TARGET: armhf

deploy:armhf:
  extends: .deploy
  variables:
    TARGET: armhf
  dependencies:
    - build:armhf

