image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - apt-get update
  - apt-get install -y make
  - docker info

ARMBuild:
  stage: build
  script:
    - make TARGET=armhf

IntelBuild:
  stage: build
  script:
    - make TARGET=x86_64

ARMDeploy:
  stage: deploy
  script:
    - docker push username/project:armhf-latest
  only:
    - master

IntelDeploy:
  stage: deploy
  script:
    - docker push username/project:x86_64-latest
  only:
    - master
